apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-front
  namespace: eks-app
  labels:
    app: eks-streamlit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-streamlit
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: eks-streamlit
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: streamlit
          image: 225989344665.dkr.ecr.us-west-2.amazonaws.com/grayscaler/example:streamlit-front-8338d9a824059682357fdf5bedc3c50e3a2d270f-
          ports:
            - name: http
              containerPort: 8501
          env:
            - name: LOGIN_URL
              value: "http://login-service:8000/login"
            - name: USER_URL
              value: "http://user-service:8000/user"
            - name: RESERVE_URL
              value: "http://reserve-service:8000/reserve"
            - name: VERIFY_URL
              value: "http://reserve-service:8000/reserve/verify_user_info"
            - name: TICKET_INFO_URL
              value: "http://reserve-service:8000/reserve/ticket"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m" # 최소 0.2 vCPU 사용
              memory: "256Mi" # 최소 256MB RAM 사용
            limits:
              cpu: "500m" # 최대 0.5 vCPU 사용
              memory: "512Mi" # 최대 512MB RAM 사용
      nodeSelector:
        kubernetes.io/os: linux
