apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: eks-app
spec:
  selector:
    app: eks-login
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
