apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-api
  namespace: eks-app
  labels:
    app: eks-login
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-login
  template:
    metadata:
      labels:
        app: eks-login
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: login
        image: 225989344665.dkr.ecr.us-west-2.amazonaws.com/hao/ticket_service:login_auto_1
        ports:
        - name: http
          containerPort: 8000
        env:
        - name: DB_IP
          value: "10.10.2.211"
        - name: DB_PASSWD
          value: "P@ssw0rd!"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"  # 최소 CPU 요청 (100m = 0.1 vCPU)
            memory: "128Mi"  # 최소 메모리 요청
          limits:
            cpu: "500m"  # 최대 CPU 사용량 (0.5 vCPU)
            memory: "256Mi"  # 최대 메모리 사용량
      nodeSelector:
        kubernetes.io/os: linux