apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: reserve-hpa
  namespace: eks-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reserve-api
  minReplicas: 3  # 최소 파드 수
  maxReplicas: 15  # 최대 파드 수
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65  # CPU 사용량 65% 초과 시 스케일업
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70  # 메모리 사용량 70% 초과 시 스케일업

