apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: eks-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: streamlit-front  # 실제 프론트엔드 Deployment 이름
  minReplicas: 2  # 최소 파드 수
  maxReplicas: 5  # 최대 파드 수
  metrics:
    - type: Resource
      resource:
        name: cpu  # CPU 사용량을 기준으로 스케일링
        target:
          type: Utilization
          averageUtilization: 50 # CPU 사용량이 50%를 초과하면 스케일HPA업