apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: eks-app  # 수정된 네임스페이스
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-api
  minReplicas: 2  # 최소 파드 수
  maxReplicas: 6  # 최대 파드 수
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75  # CPU 사용량 75% 초과 시 스케일업
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60  # 메모리 사용량 60% 초과 시 스케일업

